domain: "###ZARF_VAR_DOMAIN###"

postgres:
  # Set to false to use external postgres
  internal: true
  selector:
    cluster-name: pg-cluster
  username: confluence
  password: ""
  namespace: postgres
  port: 5432

persistence:
  confluenceInitProperties:
    storageClassName: local-path

setup:
  instanceDisplayName: Confluence
  generateRandomAdminPassword:
    # Set to false to provide your own initialAdminSecret
    enabled: true
    username: admin
    email: admin@uds.dev
    displayName: Instance Admin
  initialAdminSecret:
    secretName: confluence-initial-admin-password
    usernameKey: username
    passwordKey: password
    emailKey: email
    displayNameKey: displayName
  license:
    generateSecret: true
    secretName: confluence-license
    licenseKeyData: ""

sso:
  enabled: true
  # Options: "saml"
  protocol: saml
  groups:
    - /uds core
    - /uds core/admin
    - /uds core/auditor
  groupPermissions:
    - groupName: /uds core/admin
      permission: SYS_ADMIN
    - groupName: /uds core
      permission: LICENSED_USER
  attributes:
    username: name
    firstname: first_name
    lastname: last_name
    email: email
    groups: groups

# custom:
#    # Notice no `remoteGenerated` field here on custom internal rule
#   - direction: Ingress
#     selector:
#       app: jenkins
#     remoteNamespace: jenkins
#     remoteSelector:
#       app: jenkins
#     port: 8180
#     description: "Ingress from Jenkins"
#   # No `remoteNamespace`, `remoteSelector`, or `port` fields on rule to `remoteGenerated`
#   - direction: Egress
#     selector:
#       app: webservice
#     remoteGenerated: Anywhere
#     description: "Egress from Mattermost"
