domain: "###ZARF_VAR_DOMAIN###"

postgres:
  # Set to false to use external postgres
  internal: true
  selector:
    cluster-name: pg-cluster
  username: confluence
  password: ""
  namespace: postgres
  port: 5432

sso:
  enabled: true
  # Options: "saml", "openid_connect"
  protocol: "saml"

# Do not manually set this value. It toggles on/off multiple resources based on the desire to cluster in concert
# with the main confluence chart. It is unlikely that you will be benefited by bypassing this var.
clustering_enabled: "###ZARF_VAR_CONFLUENCE_CLUSTERING_ENABLED###"

# Session Affinity settings for Istio Destination Rule. Only applies when clustering is enabled.
sessionAffinity:
  cookieName: seraph.confluence  # https://confluence.atlassian.com/doc/confluence-cookies-160794071.html
  TTL: 0s  # Ignored unless you substitute in a custom named cookie (that Istio creates)

# custom:
#    # Notice no `remoteGenerated` field here on custom internal rule
#   - direction: Ingress
#     selector:
#       app: jenkins
#     remoteNamespace: jenkins
#     remoteSelector:
#       app: jenkins
#     port: 8180
#     description: "Ingress from Jenkins"
#   # No `remoteNamespace`, `remoteSelector`, or `port` fields on rule to `remoteGenerated`
#   - direction: Egress
#     selector:
#       app: webservice
#     remoteGenerated: Anywhere
#     description: "Egress from Mattermost"
