image:
  repository: registry1.dso.mil/ironbank/atlassian/confluence-data-center/confluence-node
  tag: "8.9.3"

monitoring:
  # Pending an upstream pr to fix jar file location to not be hardcoded:
  exposeJmxMetrics: false
  # jmxExporterImageRepo: registry1.dso.mil/ironbank/opensource/prometheus/jmx-exporter
  # jmxExporterImageTag: 0.18.0
