# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  repository: atlassian/confluence
  tag: "10.0.3"

monitoring:
  jmxExporterImageRepo: bitnami/jmx-exporter
  jmxExporterImageTag: 1.4.0
