# Namespace must be created ahead of time so postgres-operator can put the secret in an
# existing namespace. Failure to do so will cause the postgres cluster to fail and the
# UDS install will fail as the postgres cluster fails to enter the "Running" status.
kind: Namespace
apiVersion: v1
metadata:
  name: confluence
  labels:
    istio-injection: enabled
