{{- if eq .Values.setup.generateRandomAdminPassword.enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.setup.initialAdminSecret.secretName }}
  namespace: {{ .Release.Namespace }}
data:
  username: {{ b64enc .Values.setup.generateRandomAdminPassword.username }}
  email: {{ b64enc .Values.setup.generateRandomAdminPassword.email }}
  displayName: {{ b64enc .Values.setup.generateRandomAdminPassword.displayName }}
  password: {{ randAlphaNum 20 | b64enc }}
{{ end }}
