# This destination rule is required to make it so clients will to contact the same
# confluence pod over the course of any session. This is required because Confluence
# pods are stateful. If you change pods mid-process the new pod will be back at the home-page.
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: confluence-destination-rule-for-stateful-balancing
spec:
  host: confluence.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: {{ .Values.sessionAffinity.cookieName }}
          ttl: {{ .Values.sessionAffinity.TTL }}  # TTL only matters if Istio is creating the session cookie.
