{{ if .Values.clustering.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: confluence-destination-rule-clustering
spec:
  host: confluence.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          # set a new session cookie with istio per atlassian guidelines
          # note: this cookie is explicitly different than JSESSIONID, let confluence handle that
          name: CONFLUENCECONSISTENTHASH
          path: /
          ttl: 300m

{{ end }}
