{{ if .Values.clustering.enabled }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hazelcast-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hazelcast-cluster-role
subjects:
  - kind: ServiceAccount
    name: confluence        # This needs to match the name of the ServiceAccount created by the confluence helm chart.
    namespace: {{ .Release.Namespace }}   # This needs to match the namespace the confluence service account is deployed to.
{{ end }}
