---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "confluence"
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: STRICT
  portLevelMtls:
    5701:
      mode: PERMISSIVE
  selector:
    matchLabels:
      app.kubernetes.io/name: confluence
