# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if .Values.postgres.password }}
apiVersion: v1
kind: Secret
metadata:
  name: confluence-postgres
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/opaque
stringData:
  {{- if .Values.postgres.username }}
  username: {{ .Values.postgres.username | quote }}
  {{- end }}
  password: {{ .Values.postgres.password | quote }}
{{- end }}
