# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: confluence
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.sso.enabled }}
  sso:
    - name: Confluence Login
    {{- if eq .Values.sso.protocol "saml" }}
      clientId: uds-package-confluence-saml
      protocol: saml

      redirectUris:
        - "https://confluence.{{ .Values.domain }}/plugins/servlet/oidc/callback"

      defaultClientScopes:
      {{- if .Values.sso.defaultClientScopes }}
        {{- range .Values.sso.defaultClientScopes }}
          - "{{ . }}"
        {{- end }}
      {{- else }}
        - "mapper-saml-email-email"
        - "mapper-saml-firstname-first_name"
        - "mapper-saml-lastname-last_name"
        - "mapper-saml-grouplist-groups"
        - "mapper-saml-username-name"
      {{- end }}
    {{- else if eq .Values.sso.protocol "openid_connect"  }}
      clientId: uds-package-confluence-openid-connect
      protocol: openid-connect
      defaultClientScopes:
      {{- if .Values.sso.defaultClientScopes }}
        {{- range .Values.sso.defaultClientScopes }}
          - "{{ . }}"
        {{- end }}
      {{- end }}

      redirectUris:
        - "https://confluence.{{ .Values.domain }}/plugins/servlet/oidc/callback"
    {{- end }}
      groups:
        anyOf:
        {{- if .Values.sso.requiredGroups }}
          {{- range .Values.sso.requiredGroups }}
            - "{{ . }}"
          {{- end }}
        {{- end }}
  {{- end }}

  monitor:
    - selector:
        app.kubernetes.io/name: confluence
      targetPort: 9999
      portName: jmx
      path: /metrics
      description: Metrics

  network:
    serviceMesh:
      mode: {{ if .Values.clustering.enabled }}sidecar{{ else }}ambient{{ end }}
    expose:
      - service: confluence
        selector:
          app.kubernetes.io/name: confluence
        gateway: tenant
        host: confluence
        port: 80
        targetPort: 8090
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace

      - direction: Egress
        remoteGenerated: IntraNamespace

      - direction: Egress
        remoteNamespace: keycloak
        remoteSelector:
          app.kubernetes.io/name: keycloak
        selector:
          app.kubernetes.io/name: confluence
        port: 8080
        description: "SSO Internal"

      - direction: Egress
        remoteGenerated: Anywhere
        selector:
          app.kubernetes.io/name: confluence
        port: 443
        description: "SSO External"

      - direction: Egress
        selector:
          app.kubernetes.io/name: confluence
        {{- if .Values.postgres.internal }}
        remoteNamespace: {{ .Values.postgres.namespace | quote }}
        remoteSelector:
          {{ .Values.postgres.selector | toYaml | nindent 10 }}
        port: {{ .Values.postgres.port }}
        {{- else }}
        remoteGenerated: Anywhere
        {{- end }}
        description: "Confluence Postgres"

      {{ if .Values.clustering.enabled }}
      - direction: Egress
        selector:
          app.kubernetes.io/name: confluence
        remoteGenerated: KubeAPI
        description: "Provides Hazelcast with access to K8s API"

      - direction: Ingress
        selector:
          app.kubernetes.io/name: confluence
        remoteSelector:
          app.kubernetes.io/name: confluence
        remoteNamespace: {{ .Release.Namespace }}
        port: 5701
        description: "Allows Hazelcast to communicate between pods"
      {{ end }}

      # Custom rules for unanticipated scenarios
      {{- range .Values.custom }}
      - direction: {{ .direction }}
        selector:
          {{ .selector | toYaml | nindent 10 }}
        {{- if not .remoteGenerated }}
        remoteNamespace: {{ .remoteNamespace }}
        remoteSelector:
          {{ .remoteSelector | toYaml | nindent 10 }}
        port: {{ .port }}
        {{- else }}
        remoteGenerated: {{ .remoteGenerated }}
        {{- end }}
        description: {{ .description }}
      {{- end }}
