apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: confluence
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.sso }}
  sso:
    - name: Confluence Login
      clientId: uds-package-confluence
      redirectUris:
        - "https://confluence.{{ .Values.domain }}/plugins/servlet/oidc/callback"
  {{- end }}
  network:
    expose:
      - service: confluence
        podLabels:
          app.kubernetes.io/name: confluence
        gateway: tenant
        host: confluence
        port: 80
        targetPort: 8090
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace
      - direction: Egress
        remoteGenerated: IntraNamespace
      - direction: Egress
        podLabels:
          app.kubernetes.io/name: confluence
        port: 443
        description: "SSO"
      - direction: Egress
        # todo: this is over permissive, need to scope it down
        remoteGenerated: KubeAPI
      # Todo: wide open for hitting in-cluster or external postgres
      - direction: Egress
        podLabels:
          app.kubernetes.io/name: confluence
        remoteGenerated: Anywhere
