apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: confluence
  namespace: {{ .Release.Namespace }}
spec:
  network:
    expose:
      - service: confluence
        podLabels:
          app.kubernetes.io/name: confluence
        gateway: tenant
        host: confluence
        port: 80
    allow:
      # Todo: wide open for hitting in-cluster or external postgres
      - direction: Egress
        podLabels:
          app: confluence
        remoteGenerated: Anywhere
