# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: uds.dev/v1alpha1
kind: Exemption
metadata:
  name: confluence-exemptions
  namespace: uds-policy-exemptions
spec:
  exemptions:
    - description: exempt istio exclusions
      matcher:
        kind: pod
        name: ^confluence-*
        namespace: confluence
      policies:
        - RestrictIstioTrafficOverrides

{{- if .Values.synchrony.enabled }}
apiVersion: uds.dev/v1alpha1
kind: Exemption
metadata:
  name: confluence-synchrony-exemptions
  namespace: uds-policy-exemptions
spec:
  exemptions:
    - description: exempt synchrony
      matcher:
        kind: pod
        name: ^confluence-synchrony*
        namespace: confluence
      policies:
        - RequireNonRootUser
        - DropAllCapabilities
        - DisallowPrivileged
{{- end }}
