apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: confluence
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.sso }}
  sso:
    - name: Confluence Login
      clientId: uds-package-confluence
      redirectUris:
        - "https://{{ .Values.subdomain }}.{{ .Values.domain }}/plugins/servlet/oidc/callback"
  {{- end }}
  # Customize network policies and expose services via istio
  network:
    expose:
      - service: confluence
        podLabels:
          app.kubernetes.io/name: confluence
        gateway: tenant
        host: confluence
        port: 80
        targetPort: 8090
    allow:
      - direction: Ingress
        selector:
          app.kubernetes.io/name: confluence
        remoteSelector:
          app.kubernetes.io/name: confluence
        remoteNamespace: {{ .Release.Namespace }}
        port: 5801  # Hazelcast (used by nodes to form cluster)
      - direction: Egress
        selector:
          app.kubernetes.io/name: confluence
        remoteSelector:
          app.kubernetes.io/name: confluence
        remoteNamespace: {{ .Release.Namespace }}
        port: 5801  # Hazelcast (used by nodes to form cluster)
        # TODO: Add 5701 for Synchrony once enabled.

      - direction: Egress
        selector:
          app.kubernetes.io/name: confluence
        port: {{ .Values.postgres.port }}
      {{- if .Values.postgres.internal }}
        remoteNamespace: {{ .Values.postgres.namespace }}
        remoteSelector:
          {{ .Values.postgres.selector | toYaml | indent 10 }}
      {{- else }}
        # TODO: Once https://github.com/defenseunicorns/uds-core/issues/558 is resolved, this should instead be taking the external Postgres IP or domain
        # And only permitting access to that service. Right now, it permits egress to anyone, on the right port.
        remoteGenerated: Anywhere
      {{- end }}

      ### Allow monitoring to export metrics ###
      - direction: Ingress
        remoteNamespace: monitoring
        remoteSelector:
          app: prometheus
        selector:
          app: confluence
          app.kubernetes.io/component: exporter
        port: 8001 # TODO: this port number needs verified.
        description: "Confluence Exporter Monitor"

      # Custom rules for unanticipated scenarios
      {{- range .Values.custom }}
      - direction: {{ .direction }}
        selector:
          {{ .selector | toYaml | nindent 10 }}
        {{- if not .remoteGenerated }}
        remoteNamespace: {{ .remoteNamespace }}
        remoteSelector:
          {{ .remoteSelector | toYaml | nindent 10 }}
        port: {{ .port }}
        {{- else }}
        remoteGenerated: {{ .remoteGenerated }}
        {{- end }}
        description: {{ .description }}
      {{- end }}