# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

tasks:
  - name: all
    actions:
      - task: health-check
      - task: ingress

  - name: health-check
    actions:
      - description: confluence StatefulSet Health Check
        wait:
          cluster:
            kind: StatefulSet
            name: confluence
            namespace: confluence

  - name: ingress
    actions:
      - description: confluence UI Health Check
        wait:
          network:
            protocol: https
            address: confluence.uds.dev/setup/setuplicense.action
            code: 200
