shared:
  CONFLUENCE_DB_USERNAME: "confluence.confluence"

variables:
  confluence:
    confluence_db_endpoint: "pg-cluster.postgres.svc.cluster.local"
  postgres-operator:
    postgresql:
      enabled: true  # Set to false to not create the PostgreSQL resource
      teamId: "uds"
      volume:
        size: "10Gi"
      numberOfInstances: 2
      users:
        confluence.confluence: []  # database owner
      databases:
        confluencedb: confluence.confluence
      version: "13"
      ingress:
        remoteGenerated: Anywhere
